# Generated by Django 2.2.1 on 2019-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('priceChangePercent', models.FloatField(default=0.0)),
                ('weightedAvgPrice', models.FloatField(default=0.0)),
                ('volume', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date saved')),
            ],
        ),
    ]
