# Generated by Django 2.2.1 on 2019-05-25 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('position', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('priceChangePercent', models.FloatField(default=0.0)),
                ('weightedAvgPrice', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('count', models.FloatField(default=0.0)),
                ('saved_date', models.DateTimeField(default=datetime.datetime(2019, 5, 25, 15, 58, 13, 162437, tzinfo=utc))),
                ('currencyhistory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtual_currency.CurrencyHistory')),
            ],
        ),
    ]
