# Generated by Django 2.2.1 on 2019-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_currency', '0002_auto_20190523_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
